name: SheepPlugin
version: 1.0.0
main: com.company.SheepPlugin
api-version: 1.13
authors: [Mizores]
description: Sheep Plugin for Dayland.
commands:
  sheep:
    description: Create a sheep.
    usage: "Usage: /<command>"
  pig:
    description: Create a pig.
    usage: "Usage: /<command>"
  cow:
    description: Create a cow.
    usage: "Usage: /<command>"