name: SheepPlugin
version: 1.0.0
main: com.company.SheepPlugin
api-version: 1.13
authors: [Mizores]
description: Sheep Plugin for Dayland.
commands:
  sheep:
    description: Create a sheep.
    usage: "Usage: /<command>"